title: "RTSIA Experiments"
log_level: 2
inputs:
    input0:
        source: /opt/edge_ai_apps/data/images/%04d.jpg
        width: 1280
        height: 720
        index: 0
        framerate: 1
        loop: False
models:
    model0:
        model_path: /opt/model_zoo/ONR-CL-6070-mobileNetV2
        topN: 5
    model1:
        model_path: /opt/model_zoo/TFL-CL-0000-mobileNetV1-mlperf
        topN: 5
    model2:
        model_path: /opt/model_zoo/TFL-OD-2000-ssd-mobV1-coco-mlperf-300x300
        topN: 5
    model3:
        model_path: /opt/model_zoo/TFL-OD-2010-ssd-mobV2-coco-mlperf-300x300
        topN: 5
    model4:
        model_path: /opt/model_zoo/ONR-CL-6100-resNet18
        topN: 5
    model5:
        model_path: /opt/model_zoo/ONR-CL-6110-resNet50
        topN: 5

outputs:
    output0:
        sink: /opt/edge_ai_apps/data/output/images/output_image_%04d.jpg
        width: 1920
        height: 1080

flows:
    flow0:
        input: input0
        models: [model0]
        outputs: [output0]
        mosaic:
            mosaic0:
                width:  1280
                height: 720
                pos_x:  320
                pos_y:  180